export type CatalogSeed = {
  title: string;
  artists: string;
  album: string;
  year: number;
  genre: string;
  albumArt: string | null;
  durationMs: number;
  externalId?: string;
};

export type CatalogTrack = {
  id: string;
  title: string;
  artists: string;
  album: string | null;
  year: number | null;
  genre: string | null;
  albumArt: string | null;
  durationMs: number;
  externalId: string | null;
};

/** Curated library so voters can browse real songs without Spotify API. */
export const CATALOG_SEED: CatalogSeed[] = [
  {
    title: "Mr. Brightside",
    artists: "The Killers",
    album: "Hot Fuss",
    year: 2004,
    genre: "Indie Rock",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273ccdddd46119a4ff53eaf1f5d",
    durationMs: 222200,
    externalId: "3n3Ppam7vgaVa1IA8jmWRj",
  },
  {
    title: "Blinding Lights",
    artists: "The Weeknd",
    album: "After Hours",
    year: 2020,
    genre: "Synth-pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
    durationMs: 200040,
    externalId: "0VjIjW4KwUZ0kK4BkvK5jV",
  },
  {
    title: "Shape of You",
    artists: "Ed Sheeran",
    album: "÷ (Divide)",
    year: 2017,
    genre: "Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
    durationMs: 233713,
    externalId: "7qiZfU4dY1lWllzX7mPBI3",
  },
  {
    title: "High Hopes",
    artists: "Panic! At The Disco",
    album: "Pray for the Wicked",
    year: 2018,
    genre: "Pop Rock",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273c5148520a59be191ee760f63",
    durationMs: 190947,
    externalId: "1rqqCSm0Qe4I9rUvWncaom",
  },
  {
    title: "Despacito",
    artists: "Luis Fonsi, Daddy Yankee",
    album: "Vida",
    year: 2017,
    genre: "Latin Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273ef24c3fdbf856340d55cfeb2",
    durationMs: 229360,
    externalId: "6habFhsOp2NvshLv26DqMb",
  },
  {
    title: "rockstar",
    artists: "Post Malone, 21 Savage",
    album: "beerbongs & bentleys",
    year: 2018,
    genre: "Hip-Hop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273b1c4b76b385040f242fd5834",
    durationMs: 218147,
    externalId: "0e7ipj03S05BNyluHms5jb",
  },
  {
    title: "bad guy",
    artists: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    year: 2019,
    genre: "Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b27350a3147b4edd7701a876c6ce",
    durationMs: 194088,
    externalId: "2Fxmhks0bxGSBdJ92vM42m",
  },
  {
    title: "Save Your Tears",
    artists: "The Weeknd",
    album: "After Hours",
    year: 2020,
    genre: "Synth-pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
    durationMs: 215627,
    externalId: "5QO79kh1paicVfzT5RJ1GW",
  },
  {
    title: "Levitating",
    artists: "Dua Lipa",
    album: "Future Nostalgia",
    year: 2020,
    genre: "Dance-pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273d4daf28d55adff5937a95f28",
    durationMs: 203064,
    externalId: "4iJyoBOItJjl16f3YJz9Jc",
  },
  {
    title: "Sunflower",
    artists: "Post Malone, Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    genre: "Hip-Hop / Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273e2e352d89826aef6dbd5ff8f",
    durationMs: 158040,
    externalId: "3KkXRkHbMCARz0aVfEt68P",
  },
  {
    title: "Believer",
    artists: "Imagine Dragons",
    album: "Evolve",
    year: 2017,
    genre: "Pop Rock",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b2735675e616f950e9b374f9cd1d",
    durationMs: 204347,
    externalId: "0pqnGHJpmpxLKifKRmU6WP",
  },
  {
    title: "SICKO MODE",
    artists: "Travis Scott",
    album: "ASTROWORLD",
    year: 2018,
    genre: "Hip-Hop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273072e9faef2ef7b6db6389913",
    durationMs: 312820,
    externalId: "2xLMifQCjDGFmkHbpNLD9h",
  },
  {
    title: "God's Plan",
    artists: "Drake",
    album: "Scorpion",
    year: 2018,
    genre: "Hip-Hop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273f175adb4c10e9cb2e5d4d8d5",
    durationMs: 198973,
    externalId: "6DCZcSspjsKoFjzjrWowXc",
  },
  {
    title: "One Dance",
    artists: "Drake, Wizkid, Kyla",
    album: "Views",
    year: 2016,
    genre: "Dancehall / Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b2739416ed64daf84936d89e671c",
    durationMs: 173987,
    externalId: "1zi7xx7UVEFkmKfv06H8x0",
  },
  {
    title: "Industry Baby",
    artists: "Lil Nas X, Jack Harlow",
    album: "MONTERO",
    year: 2021,
    genre: "Hip-Hop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273be82673b5f79d9658ec0a9fd",
    durationMs: 212353,
    externalId: "7ytR5pREyojnnyYpKL4b0n",
  },
  {
    title: "Bohemian Rhapsody",
    artists: "Queen",
    album: "A Night at the Opera",
    year: 1975,
    genre: "Classic Rock",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273ce4f1737bc8a646c8c4bd25b",
    durationMs: 354320,
    externalId: "4u7EnebtmKWzUH433cf5Qv",
  },
  {
    title: "Smells Like Teen Spirit",
    artists: "Nirvana",
    album: "Nevermind",
    year: 1991,
    genre: "Grunge",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273e175a0463ec1aad515099805",
    durationMs: 301920,
    externalId: "5ghIJDpPoe3G90WXd7OB9l",
  },
  {
    title: "Uptown Funk",
    artists: "Mark Ronson, Bruno Mars",
    album: "Uptown Special",
    year: 2014,
    genre: "Funk / Pop",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273e419ccba0baa8bd3f3d2ab25",
    durationMs: 269667,
    externalId: "4VqPOruhp5EdPBeR92t6lQ",
  },
  {
    title: "Don't Stop Believin'",
    artists: "Journey",
    album: "Escape",
    year: 1981,
    genre: "Classic Rock",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273f3bd67035f08528d183e4518",
    durationMs: 250320,
    externalId: "1Tfq87rn573UAgQJXyiXBc",
  },
  {
    title: "One More Time",
    artists: "Daft Punk",
    album: "Discovery",
    year: 2000,
    genre: "Electronic / House",
    albumArt:
      "https://i.scdn.co/image/ab67616d0000b273b33d46dfa0d705a5c3c0b5e2",
    durationMs: 320357,
    externalId: "0DiWol3AO6WpXZgp0goxAV",
  },
  {
    title: "Toxic",
    artists: "Britney Spears",
    album: "In the Zone",
    year: 2003,
    genre: "Dance-pop",
    albumArt: null,
    durationMs: 198000,
  },
  {
    title: "Crazy in Love",
    artists: "Beyoncé, Jay-Z",
    album: "Dangerously in Love",
    year: 2003,
    genre: "R&B",
    albumArt: null,
    durationMs: 236000,
  },
  {
    title: "Hey Ya!",
    artists: "OutKast",
    album: "Speakerboxxx/The Love Below",
    year: 2003,
    genre: "Hip-Hop / Pop",
    albumArt: null,
    durationMs: 235000,
  },
  {
    title: "September",
    artists: "Earth, Wind & Fire",
    album: "The Best of Earth, Wind & Fire Vol. 1",
    year: 1978,
    genre: "Disco / Funk",
    albumArt: null,
    durationMs: 215000,
  },
  {
    title: "Dancing Queen",
    artists: "ABBA",
    album: "Arrival",
    year: 1976,
    genre: "Disco",
    albumArt: null,
    durationMs: 230600,
  },
  {
    title: "Billie Jean",
    artists: "Michael Jackson",
    album: "Thriller",
    year: 1982,
    genre: "Pop",
    albumArt: null,
    durationMs: 294400,
  },
  {
    title: "Sweet Child O' Mine",
    artists: "Guns N' Roses",
    album: "Appetite for Destruction",
    year: 1987,
    genre: "Hard Rock",
    albumArt: null,
    durationMs: 356000,
  },
  {
    title: "Take On Me",
    artists: "a-ha",
    album: "Hunting High and Low",
    year: 1985,
    genre: "Synth-pop",
    albumArt: null,
    durationMs: 225000,
  },
  {
    title: "I Wanna Dance with Somebody",
    artists: "Whitney Houston",
    album: "Whitney",
    year: 1987,
    genre: "Pop",
    albumArt: null,
    durationMs: 291000,
  },
  {
    title: "Lose Yourself",
    artists: "Eminem",
    album: "8 Mile Soundtrack",
    year: 2002,
    genre: "Hip-Hop",
    albumArt: null,
    durationMs: 326000,
  },
  {
    title: "Seven Nation Army",
    artists: "The White Stripes",
    album: "Elephant",
    year: 2003,
    genre: "Garage Rock",
    albumArt: null,
    durationMs: 232000,
  },
  {
    title: "Somebody That I Used to Know",
    artists: "Gotye, Kimbra",
    album: "Making Mirrors",
    year: 2011,
    genre: "Indie Pop",
    albumArt: null,
    durationMs: 244000,
  },
  {
    title: "Rolling in the Deep",
    artists: "Adele",
    album: "21",
    year: 2010,
    genre: "Soul / Pop",
    albumArt: null,
    durationMs: 228000,
  },
  {
    title: "Shake It Off",
    artists: "Taylor Swift",
    album: "1989",
    year: 2014,
    genre: "Pop",
    albumArt: null,
    durationMs: 219200,
  },
  {
    title: "Happy",
    artists: "Pharrell Williams",
    album: "G I R L",
    year: 2013,
    genre: "Pop / Soul",
    albumArt: null,
    durationMs: 233000,
  },
  {
    title: "Get Lucky",
    artists: "Daft Punk, Pharrell Williams",
    album: "Random Access Memories",
    year: 2013,
    genre: "Disco / Funk",
    albumArt: null,
    durationMs: 248000,
  },
  {
    title: "Can't Stop the Feeling!",
    artists: "Justin Timberlake",
    album: "Trolls Soundtrack",
    year: 2016,
    genre: "Pop / Disco",
    albumArt: null,
    durationMs: 236000,
  },
  {
    title: "Watermelon Sugar",
    artists: "Harry Styles",
    album: "Fine Line",
    year: 2019,
    genre: "Pop Rock",
    albumArt: null,
    durationMs: 174000,
  },
  {
    title: "As It Was",
    artists: "Harry Styles",
    album: "Harry's House",
    year: 2022,
    genre: "Pop",
    albumArt: null,
    durationMs: 167000,
  },
  {
    title: "Anti-Hero",
    artists: "Taylor Swift",
    album: "Midnights",
    year: 2022,
    genre: "Pop",
    albumArt: null,
    durationMs: 200690,
  },
  {
    title: "Flowers",
    artists: "Miley Cyrus",
    album: "Endless Summer Vacation",
    year: 2023,
    genre: "Pop",
    albumArt: null,
    durationMs: 200400,
  },
  {
    title: "Espresso",
    artists: "Sabrina Carpenter",
    album: "Short n' Sweet",
    year: 2024,
    genre: "Pop",
    albumArt: null,
    durationMs: 175000,
  },
  {
    title: "Good as Hell",
    artists: "Lizzo",
    album: "Cuz I Love You",
    year: 2019,
    genre: "Pop / R&B",
    albumArt: null,
    durationMs: 159000,
  },
  {
    title: "Old Town Road",
    artists: "Lil Nas X, Billy Ray Cyrus",
    album: "7 EP",
    year: 2019,
    genre: "Country Trap",
    albumArt: null,
    durationMs: 157000,
  },
  {
    title: "Stayin' Alive",
    artists: "Bee Gees",
    album: "Saturday Night Fever",
    year: 1977,
    genre: "Disco",
    albumArt: null,
    durationMs: 285000,
  },
  {
    title: "I Want It That Way",
    artists: "Backstreet Boys",
    album: "Millennium",
    year: 1999,
    genre: "Boy Band / Pop",
    albumArt: null,
    durationMs: 213000,
  },
  {
    title: "Wonderwall",
    artists: "Oasis",
    album: "(What's the Story) Morning Glory?",
    year: 1995,
    genre: "Britpop",
    albumArt: null,
    durationMs: 258000,
  },
  {
    title: "Hotel California",
    artists: "Eagles",
    album: "Hotel California",
    year: 1976,
    genre: "Classic Rock",
    albumArt: null,
    durationMs: 391000,
  },
  {
    title: "Africa",
    artists: "Toto",
    album: "Toto IV",
    year: 1982,
    genre: "Soft Rock",
    albumArt: null,
    durationMs: 295000,
  },
  {
    title: "Everybody Wants To Rule The World",
    artists: "Tears for Fears",
    album: "Songs from the Big Chair",
    year: 1985,
    genre: "New Wave",
    albumArt: null,
    durationMs: 251000,
  },
  {
    title: "Feel Good Inc.",
    artists: "Gorillaz",
    album: "Demon Days",
    year: 2005,
    genre: "Alternative Hip-Hop",
    albumArt: null,
    durationMs: 222000,
  },
  {
    title: "Clocks",
    artists: "Coldplay",
    album: "A Rush of Blood to the Head",
    year: 2002,
    genre: "Alternative Rock",
    albumArt: null,
    durationMs: 307000,
  },
  {
    title: "Yellow",
    artists: "Coldplay",
    album: "Parachutes",
    year: 2000,
    genre: "Alternative Rock",
    albumArt: null,
    durationMs: 266000,
  },
  {
    title: "Use Somebody",
    artists: "Kings of Leon",
    album: "Only by the Night",
    year: 2008,
    genre: "Alternative Rock",
    albumArt: null,
    durationMs: 231000,
  },
  {
    title: "Pumped Up Kicks",
    artists: "Foster the People",
    album: "Torches",
    year: 2010,
    genre: "Indie Pop",
    albumArt: null,
    durationMs: 240000,
  },
  {
    title: "Radioactive",
    artists: "Imagine Dragons",
    album: "Night Visions",
    year: 2012,
    genre: "Pop Rock",
    albumArt: null,
    durationMs: 186000,
  },
  {
    title: "Counting Stars",
    artists: "OneRepublic",
    album: "Native",
    year: 2013,
    genre: "Pop Rock",
    albumArt: null,
    durationMs: 257000,
  },
  {
    title: "Shut Up and Dance",
    artists: "WALK THE MOON",
    album: "Talking Is Hard",
    year: 2014,
    genre: "Indie Pop",
    albumArt: null,
    durationMs: 199000,
  },
  {
    title: "Cake By The Ocean",
    artists: "DNCE",
    album: "DNCE",
    year: 2015,
    genre: "Pop / Funk",
    albumArt: null,
    durationMs: 219000,
  },
  {
    title: "Cheap Thrills",
    artists: "Sia",
    album: "This Is Acting",
    year: 2016,
    genre: "Pop",
    albumArt: null,
    durationMs: 211000,
  },
];
